Setup and mobile first
DevKaranJ/Techfolio pull request #1
Opened 2023-07-04 16:51 UTC by DevKaranJ

This pull request includes the completed work for the first milestone of the portfolio website project. The following changes have been made:

- Set up the repository with the correct linter configuration to ensure error-free code.
- Implemented the toolbar (or header) section using flexbox for proper layout.
- Created the headline section following the design from the chosen template in Figma.
- Applied the design elements accurately, including fonts, colors, images, text, and margins.

Please review the changes made in this pull request for further details and provide feedback if necessary.

2023-07-04 17:07 UTC, Strangeal reviewed
Hi @DevKaranJ, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] It appears that your submitted project is missing this essential component. To rectify this, kindly consider the following improvements:
*  Utilize the [README](https://github.com/microverseinc/readme-template) template provided in the project requirements, This will ensure consistency and completeness in your documentation. 
*  Customize the template to suit your project details. Provide a clear and concise overview of your project, including its key features, future features, and any relevant instructions or prerequisites for users. 
*  Consider consuming sections such as installation instructions, usage examples, configuration details, and information about any external dependencies or libraries used. Include information about the project's license, copyright, or any other legal considerations. 
* Proofread and format your README to ensure it is easy to read, well-organized, and free of errors. Remember, documenting your project through a professional README is crucial for other developers to understand, use, and contribute to your project effectively.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-07-04 18:12 UTC, TadesseDev requested changes
### Hi @DevKaranJ 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![212094426-b41dd457-c9db-4ab3-bbe9-176dd8dd08b7](https://user-images.githubusercontent.com/69077061/212385281-4797c58a-d358-423a-aa7c-832c22203865.gif)




## Highlights
 - [x] Good job overall following the template design ✅
 - [x]  Correct GitHub Flow  ✅
 - [x]  Good commit history  ✅
 - [x]  Good PR title/description  ✅
 - [x]  All linters passed  ✅
 
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-04 18:12 UTC, TadesseDev commented on index.html
> +                    Glad to see you!</h2>
- [ ] Dear @DevKaranJ, This text is the main content of the page and to emphasize this we should be using an `h1` tag. If you want that google (and other search engines) to know about a specific topic, in this case, you, use an `h1` tag. [Check this link](https://www.reliablesoft.net/h1-tag/) for more info.

2023-07-04 18:12 UTC, TadesseDev commented on index.html
> +                    Glad to see you!</h2>
- [ ] It's great you have added the background image and aligned it well, but I could see some misplaced and I would love to suggest some changes to it so that we can have an identical background with the figma design.  Please remember, as a frontend engineers we are expected to deliver a webpage which Is almost identical to the given design. 

### Your design 
![image](https://github.com/DevKaranJ/Techfolio/assets/69077061/dc42a908-2289-4f2c-8e28-cab82a892b9d)

### Figma design 
![image](https://github.com/DevKaranJ/Techfolio/assets/69077061/64cf16e8-0e6b-463c-8432-6830b3df8e35)

2023-07-05 06:11 UTC, brainconnect93 approved these changes
## Status: Approved :heavy_check_mark:

Hi @DevKaranJ, 👋 👋  

Your project is complete! Great job for following the project requirement🥇and implementing the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 


<img src="https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif" width="600px" height="300px">

### To Highlight :1st_place_medal: 

- Descriptive Pull Request title and summary. ✔️  
- Portfolio: setup and mobile-first ✔️  
- Follow the Figma Design Template ✔️  
- Touchable mobile screen size of `375px` ✔️  
- Good use of GitHub flow ✔️

## Optional changes

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-05 06:11 UTC, brainconnect93 commented on index.html
> +                <img src="./resource/LETSCONNECT.svg" alt="letConnect">
- [ ] [OPTIONAL] Hello @DevKaranJ, I would kindly suggest you make the `LET'S CONNECT` a text rather than importing it as an image. This is for semantics and SEO reasons. And be sure the text aligned vertically on a straight line with the other text as seen in the original Figma design.

2023-07-05 06:42 UTC, merged