Desktop version
DevKaranJ/Techfolio pull request #4
Opened 2023-07-14 08:29 UTC by DevKaranJ

2023-07-14 18:05 UTC, AbayomiOlaoye requested changes
## STATUS: CHANGE REQUIRED ♻️ 

Hi @DevKaranJ :wave: , 

Good job with this milestone so far! What a brilliant attempt!!
There are just a few more issues to work on before moving on to the next project but you are almost there!

![so_close](https://camo.githubusercontent.com/0c690ab997907a8c79afe7e695c891f6398cdbef93eaf8ce19f652ff321b54f8/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f744b797263304e546c4563475764546870342f67697068792e676966)

## Highlights
- Descriptive Pull Request message :heavy_check_mark: 
- Good use of GitHub flow :heavy_check_mark:
- Good attempt :heavy_check_mark: 
- Meaningful commit messages :heavy_check_mark: 
- No linter error :heavy_check_mark: 
- Descriptive ReadMe documentation :heavy_check_mark: 

## Required Changes ♻️
- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-14 18:05 UTC, AbayomiOlaoye commented on style.css
> +}
- Hey Haran! :wink: That was  so close :clap: :clap: 
- [ ] You have made commendable efforts on this but I think you could still improve on what we have now. The page is not correctly responsive in such a way that every user on every device is able to interact and navigate your page impressively. Check out this [video](https://watch.screencastify.com/v/JDdtbcx4XSPQ7faAPnf3) and see what I'm talking about.
  - [ ] In the video, you will see that your elements are not really responsive in terms of `font-sizes`, `color`, outline on project cards, etc. with regards to screen sizes as we have in the Figma design:
  - Desktop View:  
![image](https://github.com/DevKaranJ/Techfolio/assets/99715640/ef8bbfd4-bbb7-4e9d-be98-02963c8167e1)
  - Mobile View:
![image](https://github.com/DevKaranJ/Techfolio/assets/99715640/ed8c1d8d-f7d5-4359-acf0-a8ab529a444a)

  - [ ] Your project cards are not responsively centralized
  - [ ] We have an overflow on the y-axis
  - [ ] Your list of `language`, `skills`, and `frameworks` seems not to be responsive

- Kindly check the Figma design again and see how to improve what you have coded

2023-07-15 09:55 UTC, tufoinnkuo10 requested changes
Hi @DevKaranJ 
There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally

Required Changes ♻️
Check the comments under the review
Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2023-07-15 09:55 UTC, tufoinnkuo10 commented on index.html
> +        <footer class="footer">
- [ ] please the headline, the about and contact section should be centralized and responsive as well. check here for the orignal design to be followed. nice work
yours
![Screenshot (1245)_LI](https://github.com/DevKaranJ/Techfolio/assets/65298048/84f9bd8b-a06d-4fc5-9384-8545f72768bd)

![Screenshot (1247)_LI](https://github.com/DevKaranJ/Techfolio/assets/65298048/f0e1dbad-3301-46bd-9ec4-9e02798b993b)

![Screenshot (1248)_LI](https://github.com/DevKaranJ/Techfolio/assets/65298048/0f469884-cc3f-4a95-9744-f300bedc25a2)

2023-07-15 09:55 UTC, tufoinnkuo10 commented on index.html
> +                        <div class="workHeadline2">
- [ ] like the previous reviewer noted, your cards and all sections of your desktop version are not centralize. Kindly edit and remove the max-width you gave some sections, the margin left you gave them, so they can be centralized. The card content should also be worked in terms of padding, margins, spacing and aligning the content. Please try as much as possible to follow the [figma ](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?type=design&node-id=0-1&mode=design&t=DE14pRV1XoxpS1y8-0)design. 
- [optional] kindly add the hover and pressed effects on your buttons as in the original version. 
yours
![Screenshot (1246)_LI](https://github.com/DevKaranJ/Techfolio/assets/65298048/ce11a105-e9c7-4bf0-8bd4-bd87b5f395d0)
figma
![Screenshot (1249)](https://github.com/DevKaranJ/Techfolio/assets/65298048/185c42ba-7e43-4a75-b788-93398893cd36)

2023-07-15 18:44 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle: 

Hi @DevKaranJ, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-15 18:44 UTC, Qoosim commented on index.html
>                      <p class="heading">
- [ ] As noted by the previous reviewers, the project card is supposed to be at the center of your page and the width of the project info inside the card need to be increased too. Kindly check the screenshots below and walk your design alongside the figma design.


### Your Design

![your-project](https://github.com/DevKaranJ/Techfolio/assets/26597432/9d408dd3-0d26-4bca-9cfe-f64110ba2913)

### Figma Design

![temp-project](https://github.com/DevKaranJ/Techfolio/assets/26597432/a0d8405a-8c64-4d9b-8fc8-b6c1370fca3f)


- [ ] As noted by the previous reviewers, your about myself section does not match the figma design. Kindly check the screenshots below and walk your design alongside the figma design.

### Your Design

![your-about-me](https://github.com/DevKaranJ/Techfolio/assets/26597432/8468b163-ebd1-4814-b5ea-7b67cd4512b7)

### Figma Design

![temp-about-me](https://github.com/DevKaranJ/Techfolio/assets/26597432/58f7c2f6-72ff-4bbe-9bb5-c8934e138f5a)

- [ ]  While working on the desktop version of your portfolio, kindly ensure that your mobile version styling is not affected. I wish you the best.

2023-07-15 19:38 UTC, Kamba56 approved these changes
Hi @DevKaranJ, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏
## Highlights
- [x] Great job using media queries to make page responsive!👏👏👏
- [x] Great job using grid and flexbox to layout contents!👏👏👏
- [x] !👏👏👏

## Optional suggestions

- [OPTIONAL] Your portfolio looks great up to screen size with a width of 1024px. Your portfolio starts breaking at screen sizes above 1100px. Kindly look into that so that your project can be responsive on all screensizes.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-16 10:43 UTC, merged